from django.urls import path 
from . import views 

urlpatterns = [
    path('', views.index),
    path('index', views.index),
    path('index/', views.index),
    path('create_user', views.create_user),
    path('login', views.login),
    path('logout', views.logout),
    path('user/<int:user_id>', views.user),
    path('user/<int:user_id>/', views.user),
    path('user/<int:user_id>/edit', views.user_edit),
    path('user/<int:user_id>/edit/', views.user_edit),
    path('user/<int:user_id>/update', views.user_update),
    path('dashboard', views.dashboard),
    path('dashboard/', views.dashboard),
    path('new_group', views.new_group),
    path('new_group/', views.new_group),
    path('new_group/create', views.create_group),
    path('group/<int:group_id>', views.group),
    path('group/<int:group_id>/', views.group),
    path('group/<int:group_id>/edit', views.group_edit),
    path('group/<int:group_id>/edit/', views.group_edit),
    path('group/<int:group_id>/update', views.group_update),
    path('group/<int:group_id>/delete', views.group_delete),
    path('group/<int:group_id>/open', views.group_open),
    path('group/<int:group_id>/close', views.group_close),
    path('group/<int:group_id>/add_dm', views.add_dm),
    path('group/<int:group_id>/remove_dm', views.remove_dm),
    path('group/search', views.group_search),
    path('group/search/', views.group_search),
    path('group/<int:group_id>/join', views.group_join),
    path('group/<int:group_id>/leave', views.group_leave),
    path('schedule/create', views.session_create),
    path('schedule/<int:group_id>', views.schedule),
    path('schedule/<int:group_id>/', views.schedule),
    path('schedule/<int:group_id>/edit', views.schedule_edit),
    path('schedule/<int:group_id>/edit/', views.schedule_edit),
    path('schedule/<int:group_id>/update', views.schedule_update),
    path('schedule/<int:group_id>/delete', views.schedule_delete),
    path('archive/<int:group_id>', views.archive),
    path('archive/<int:group_id>/', views.archive),
    path('session/<int:session_id>/group/<int:group_id>', views.session),
    path('session/<int:session_id>/group/<int:group_id>/', views.session),
    path('session/<int:session_id>/group/<int:group_id>/edit', views.session_edit),
    path('session/<int:session_id>/group/<int:group_id>/edit/', views.session_edit),
    path('session/<int:session_id>/group/<int:group_id>/update', views.session_update),
    path('archive_session/<int:session_id>', views.archive_session),
    ]