# Generated by Django 2.2 on 2021-09-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
